//! Quantized-format contract shared by RIR and the ggml fork.
//!
//! Each row of the canonical table is the source for
//! `generated/rir/quant/ggml-retro-quant.h` - the X-macro header ggml, MSL and
//! the Vulkan shader generator already consume, copied byte-for-byte into the
//! fork so the fork stays buildable standalone.
//!
//! The table itself lives in `rir-core` (`rir_core::quant_formats`), which also
//! expands it into `QuantType` and its descriptors for the Rust side. Nothing
//! is generated *into* Rust: this module only crosses the language boundary.
//!
//! Adding a format requires one row there; both tables and their test matrices
//! follow.

use rir_core::QuantFormat;

/// Emits `ggml-retro-quant.h`, the X-macro header consumed by ggml, by
/// `ggml-metal.metal` and by the Vulkan shader generator.
///
/// Macro-only by design: `ggml-metal.metal` is a consumer, so the file must
/// stay legal MSL - no include, no type, no prototype.
///
/// The header's prose lives **here**, in the generator, and that is the whole
/// point of the "DO NOT EDIT MANUALLY" line it prints. The paragraph on the ten
/// hand-written copies was once edited into the emitted file directly, which
/// left `regenerating_produces_no_diff` and
/// `the_fork_copies_match_the_generated_artefacts` red without a single table
/// byte differing - and while they are red they protect nothing.
pub fn emit_ggml_header(formats: &[QuantFormat]) -> String {
    let dequant: Vec<&QuantFormat> = formats.iter().filter(|f| f.ops.dequant).collect();
    let extra: Vec<&QuantFormat> = formats
        .iter()
        .filter(|f| f.ops.out_prod && !f.ops.dequant)
        .collect();

    let row = |f: &QuantFormat| {
        format!(
            "    X({:<20} {:<20} {:<19} {:<9} {})",
            format!("{},", f.ggml_type),
            format!("{},", f.metal_block),
            format!("{},", f.nl),
            format!("{},", f.name),
            f.vk_name(),
        )
    };
    let block = |rows: &[&QuantFormat]| {
        let mut lines: Vec<String> = rows.iter().map(|f| row(f)).collect();
        let width = lines.iter().map(|l| l.len()).max().unwrap_or(0);
        let n = lines.len();
        for (i, l) in lines.iter_mut().enumerate() {
            if i + 1 < n {
                let pad = width - l.len();
                l.push_str(&" ".repeat(pad + 1));
                l.push('\\');
            }
        }
        lines.join("\n")
    };

    let mut s = String::new();
    s.push_str(
        r#"// Generated by rir-gen - DO NOT EDIT MANUALLY.
// Source of truth: rir_core::quant_formats() in the retrograd repository.
// The same rows expand, in rir-core and at compile time, into the Rust
// registry, so a format cannot be known to one side and not the other.
#pragma once

// retro delta: the list of types a training kernel can decode in place.
//
// Two training ops read a frozen, quantized tensor directly: OUT_PROD (src0 is
// the frozen projection whose input gradient we need, dx = out_prod(W, dy)) and
// FUSED_SPARSE_CE[_BACK] (the frozen output head). Which types each could decode
// The supported types are declared in one row and expanded per consumer.
// Macro-only by design:
// ggml-metal.metal is a consumer, so this header must stay legal MSL - no
// #include, no types, no prototypes.
//
// Columns:
//   TYPE    ggml_type enum value
//   BLK     Metal block struct for one quantization block
//   NL      16-value chunks per block, i.e. QK/16
//   NAME    ggml_type_name() spelling; suffixes dequantize_<NAME> and the
//           kernel_<op>_<NAME> pipeline names
//   VKNAME  lowercased NAME; suffixes Vulkan shader/pipeline names and feeds
//           DATA_A_<upper(VKNAME)>
//
// (BLK, NL, dequantize_<NAME>) is the triple kernel_mul_mm already instantiates
// with for every quant type: dequantize_<NAME>(blk, il, reg) fills the 16
// consecutive elements at il*16 within a block of NL*16. That uniform contract is
// what lets one template cover every row.
//
// A type belongs here only if the CPU has a path for it in both ops (so a parity
// test has an oracle), dequantize_<NAME> exists in ggml-metal.metal and
// dequantize()/get_dm() exist for DATA_A_<upper(VKNAME)> in dequant_funcs.glsl,
// and real GGUF files use it.
//
// Deliberately excluded from this Metal/CE table:
//   IQ1_S, IQ1_M   1.5-1.75 bpw; now covered and parity-tested by OUT_PROD only.
//   NVFP4          Blackwell-oriented; now covered by OUT_PROD only.
//   Q1_0, Q2_0     Very recent; now covered by OUT_PROD only.
// Deliberately excluded from every table:
//   BF16           CPU and CUDA decode it in OUT_PROD now. Metal and Vulkan
//                  are what a row here would claim, and neither carries a
//                  dequantize_bf16 tile loader yet.
//   TQ1_0, TQ2_0   CUDA and Vulkan expose no dequantize_tq* primitive to reuse.
//
// F32 is not a row: it needs no decoding and both ops give it a cheaper dedicated
// path. Sites that want it list it explicitly alongside the expansion.

// Spelled QK_NL in ggml-metal.metal; not reused so this header stays include-free.
#define GGML_RETRO_NL_256 16

//        TYPE                 BLK             NL                  NAME      VKNAME
#define GGML_RETRO_DEQUANT_TYPES(X) \
"#,
    );
    s.push_str(&block(&dequant));
    s.push_str("\n\n");
    s.push_str(
        "// Row count, for the probe ABI and for tests asserting they enumerate the whole\n\
         // table rather than a stale copy of it.\n",
    );
    s.push_str(&format!(
        "#define GGML_RETRO_DEQUANT_TYPE_COUNT {}\n\n",
        dequant.len()
    ));
    s.push_str(
        "// OUT_PROD Q2 is also implemented on CPU, CUDA and Vulkan for the rarer formats\n\
         // below.  They are intentionally not folded into GGML_RETRO_DEQUANT_TYPES:\n\
         // that table is shared with Metal and with fused sparse CE, whose support policy\n\
         // is narrower.  Keeping the extension declarative avoids a hand-written type\n\
         // switch in each of the three Q2 backends.\n\
         #define GGML_RETRO_OUT_PROD_EXTRA_TYPES(X) \\\n",
    );
    s.push_str(&block(&extra));
    s.push_str("\n\n");
    s.push_str(
        "#define GGML_RETRO_OUT_PROD_TYPES(X) \\\n    \
         GGML_RETRO_DEQUANT_TYPES(X)      \\\n    \
         GGML_RETRO_OUT_PROD_EXTRA_TYPES(X)\n\n",
    );
    s.push_str(&format!(
        "#define GGML_RETRO_OUT_PROD_TYPE_COUNT {}\n",
        dequant.len() + extra.len()
    ));
    s
}
