//! CPU emitter: Loop IR to standalone Rust source.
//!
//! Emitted files have no runtime dependencies on RIR crates. They define their
//! own `TensorRef`, `TensorRefBytes`, and `TensorRefMut` types, F16-to-F32
//! conversion when required by a quantized loader, and one public function per
//! kernel. Strides are ggml-style byte strides. The emitter only prints Loop IR.

use rir_core::{Access, DType};
use rir_lower::{LoopKernel, MemType, VarId};

use crate::EmitError;

mod addr;
mod expr;
mod stmts;

/// The widening conversion printed into generated Rust.
///
/// **The third of three deliberate copies**, and the
/// one that has no choice: emitted files have no dependency on any RIR crate, so
/// this cannot call `rir_core::quant::half_to_f32` even if sharing were
/// desirable. It is a copy *and* an independent witness, which is why the test
/// that guards it compares the three over the whole input space
/// (`rir-kernels/tests/f16_oracles.rs`) instead of asserting they are one
/// function.
const F16_HELPER: &str = r#"fn f16_to_f32(h: u16) -> f32 {
    let sign = ((h >> 15) & 1) as u32;
    let exp = ((h >> 10) & 0x1F) as u32;
    let man = (h & 0x3FF) as u32;
    let bits = if exp == 0 {
        if man == 0 {
            sign << 31
        } else {
            // A subnormal half is `man · 2^-24`; renormalizing shifts `e`
            // times, so the binary32 exponent field is `113 - e` - 103 for the
            // smallest half, which is 2^-24. It read `112 - e` until fixed,
            // i.e. every F16 subnormal decoded one binade too small.
            let mut m = man;
            let mut e: i32 = 0;
            while m & 0x400 == 0 {
                m <<= 1;
                e += 1;
            }
            (sign << 31) | (((113 - e) as u32) << 23) | ((m & 0x3FF) << 13)
        }
    } else if exp == 0x1F {
        (sign << 31) | 0x7F80_0000 | (man << 13)
    } else {
        (sign << 31) | ((exp + 112) << 23) | (man << 13)
    };
    f32::from_bits(bits)
}
"#;

/// The narrowing conversion printed into generated Rust: round to nearest even,
/// the rounding `half(x)` and `float16_t(x)` perform.
///
/// Same status as `F16_HELPER` above, with one copy fewer to compare against:
/// only the interpreter has a second narrowing (`rir_lower::interp::f32_to_f16`),
/// because the canonical tables are read and never written.
const F32_TO_F16_HELPER: &str = r#"fn f32_to_f16(f: f32) -> u16 {
    let bits = f.to_bits();
    let sign = ((bits >> 16) & 0x8000) as u16;
    let exp = ((bits >> 23) & 0xFF) as i32;
    let man = bits & 0x007F_FFFF;
    if exp == 0xFF {
        // Inf stays Inf; a NaN keeps a non-zero mantissa.
        return sign | 0x7C00 | if man != 0 { 0x0200 } else { 0 };
    }
    let e = exp - 127 + 15;
    if e >= 0x1F {
        return sign | 0x7C00;
    }
    if e <= 0 {
        if e < -10 {
            return sign;
        }
        // Subnormal: shift the implicit one back in, then round to nearest even.
        let m = man | 0x0080_0000;
        let shift = (14 - e) as u32;
        let half = (m >> shift) as u16;
        let rest = m & ((1 << shift) - 1);
        let tie = 1u32 << (shift - 1);
        let round = u16::from(rest > tie || (rest == tie && half & 1 == 1));
        return sign | (half + round);
    }
    let half = ((e as u32) << 10) as u16 | (man >> 13) as u16;
    let rest = man & 0x1FFF;
    let round = u16::from(rest > 0x1000 || (rest == 0x1000 && half & 1 == 1));
    sign | (half + round)
}
"#;

struct CpuPrinter<'k> {
    k: &'k LoopKernel,
    out: String,
    indent: usize,
}

impl<'k> CpuPrinter<'k> {
    fn line(&mut self, s: &str) {
        for _ in 0..self.indent {
            self.out.push_str("    ");
        }
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn var(&self, v: VarId) -> &str {
        &self.k.var_names[v.0 as usize]
    }
}

pub fn emit_cpu(k: &LoopKernel) -> Result<String, EmitError> {
    let mut p = CpuPrinter {
        k,
        out: String::new(),
        indent: 0,
    };

    p.line("// Generated by rir-gen - DO NOT EDIT MANUALLY.");
    p.line(&format!(
        "// Kernel: {} (backend {}, reduction {}).",
        k.name,
        k.schedule.backend().name(),
        k.schedule.reduction().name()
    ));
    p.line("// Strides are bytes in ggml order (nb[0] is the innermost dimension stride;");
    p.line("// for a quantized tensor, nb[0] is the block size).");
    p.line("");
    p.line("#[derive(Clone, Copy)]");
    p.line("pub struct TensorRef<'a> {");
    p.line("    pub data: &'a [f32],");
    p.line("    pub nb: [usize; 4],");
    p.line("}");
    p.line("");
    let any_bytes = k
        .args
        .iter()
        .any(|a| a.access == Access::Read && matches!(a.ty.dtype, DType::Quant(_) | DType::F16));
    if any_bytes {
        p.line("#[derive(Clone, Copy)]");
        p.line("pub struct TensorRefBytes<'a> {");
        p.line("    pub data: &'a [u8],");
        p.line("    pub nb: [usize; 4],");
        p.line("}");
        p.line("");
    }
    // Declare each **written element type actually present**. The two types are
    // independent because a kernel may write an F32 destination and an F16 one
    // at once (ADR-3 section 6).
    let writes = |dtype: DType| {
        k.args
            .iter()
            .any(|a| a.access == Access::Write && a.ty.dtype == dtype)
    };
    let writes_f32 = writes(DType::F32);
    let writes_f16 = writes(DType::F16);
    if writes_f32 {
        p.line("pub struct TensorRefMut<'a> {");
        p.line("    pub data: &'a mut [f32],");
        p.line("    pub nb: [usize; 4],");
        p.line("}");
        p.line("");
    }
    if writes_f16 {
        p.line("pub struct TensorRefBytesMut<'a> {");
        p.line("    pub data: &'a mut [u8],");
        p.line("    pub nb: [usize; 4],");
        p.line("}");
        p.line("");
    }
    // Whether a **read** access is F16, derived from the same query the buffer
    // declarations use (`LoopKernel::mem_types`) rather than from a walker of
    // its own. The walker that stood here missed `ForTiled`/`ForConst`, which is
    // where the block header of a segmented quantized reduction now sits: it
    // printed the call and not the helper. A statement
    // list is exactly what nobody should be enumerating twice.
    let reads_f16 = k
        .args
        .iter()
        .zip(k.mem_types())
        .any(|(a, tys)| a.access == Access::Read && tys.contains(&MemType::F16));
    if reads_f16 {
        p.out.push_str(F16_HELPER);
        p.line("");
    }
    if writes_f16 {
        p.out.push_str(F32_TO_F16_HELPER);
        p.line("");
    }
    // Constant tables, derived from the loop nest and printed as floats - the
    // same values every backend prints, so the oracle and the shader index the
    // same numbers (ADR-3 section 4).
    for lut in k.luts() {
        let values: Vec<String> = lut.values().iter().map(|v| format!("{v:?}f32")).collect();
        p.line(&format!(
            "const {}: [f32; {}] = [{}];",
            lut.symbol().to_uppercase(),
            values.len(),
            values.join(", ")
        ));
        p.line("");
    }

    // Signature order: axis extents, arguments, then parameters.
    let mut sig: Vec<String> = Vec::new();
    for a in &k.axes {
        sig.push(format!("n_{}: usize", a.name));
    }
    for a in &k.args {
        let ty = match (a.access, a.ty.dtype) {
            // Both a quantized block and an F16 element are read as bytes: the
            // emitted source holds no `f16` type, and the decoding - or the
            // widening - is printed at the access.
            (Access::Read, DType::Quant(_) | DType::F16) => "TensorRefBytes",
            (Access::Read, _) => "TensorRef",
            (Access::Write, DType::F16) => "TensorRefBytesMut",
            (Access::Write, _) => "TensorRefMut",
        };
        sig.push(format!("{}: {}", a.name, ty));
    }
    for pd in &k.params {
        sig.push(format!("{}: {}", pd.name, pd.ty.name()));
    }

    p.line(&format!("pub fn {}(", k.name));
    for s in &sig {
        p.line(&format!("    {s},"));
    }
    p.line(") {");
    p.indent = 1;
    let body = k.body.clone();
    p.stmts(&body)?;
    p.indent = 0;
    p.line("}");

    Ok(p.out)
}

#[cfg(test)]
mod tests {
    use rir_core::{Extent, KernelBuilder, TensorType};
    use rir_lower::Schedule;

    /// A kernel writing **both** an F32 and an F16 destination must declare both
    /// mutable reference types, because its signature names both.
    ///
    /// It is a synthetic kernel because no registered kernel has this shape;
    /// the test protects the independent declarations from regressing.
    #[test]
    fn a_kernel_with_two_output_types_declares_both() {
        let mut k = KernelBuilder::new("two_outputs");
        let x = k.input("x", TensorType::f32(2));
        let wide = k.output("wide", TensorType::f32(2));
        let half = k.output("half", TensorType::f16(2));
        let col = k.axis("col", Extent::Dim { arg: x, dim: 0 });
        let row = k.axis("row", Extent::Dim { arg: x, dim: 1 });
        let v = k.read(x, &[col, row]);
        k.write(wide, &[col, row], v);
        k.write(half, &[col, row], v);
        let kernel = k.finish().expect("valid kernel");
        let lk = rir_lower::lower(&kernel, Schedule::cpu_serial()).expect("lowering");
        let src = super::emit_cpu(&lk).expect("emission");

        assert!(src.contains("pub struct TensorRefMut<'a> {"), "{src}");
        assert!(src.contains("pub struct TensorRefBytesMut<'a> {"), "{src}");
        // And the signature names each destination with the type just declared.
        assert!(src.contains("wide: TensorRefMut,"), "{src}");
        assert!(src.contains("half: TensorRefBytesMut,"), "{src}");
    }

    /// The other half of the same rule: a kernel with one F32 output declares
    /// only `TensorRefMut`. Without this the fix above could have been "declare
    /// both, always", which would put an unused byte view in every generated
    /// file.
    #[test]
    fn a_kernel_with_one_output_type_declares_only_that_one() {
        let mut k = KernelBuilder::new("one_output");
        let x = k.input("x", TensorType::f32(2));
        let dst = k.output("dst", TensorType::f32(2));
        let col = k.axis("col", Extent::Dim { arg: x, dim: 0 });
        let row = k.axis("row", Extent::Dim { arg: x, dim: 1 });
        let v = k.read(x, &[col, row]);
        k.write(dst, &[col, row], v);
        let kernel = k.finish().expect("valid kernel");
        let lk = rir_lower::lower(&kernel, Schedule::cpu_serial()).expect("lowering");
        let src = super::emit_cpu(&lk).expect("emission");

        assert!(src.contains("pub struct TensorRefMut<'a> {"), "{src}");
        assert!(!src.contains("TensorRefBytesMut"), "{src}");
    }
}
