//! Vulkan emitter: Loop IR to compute GLSL (`kernel.comp`).
//!
//! Like the other emitters, this is a pure printer. Push-constant layout for
//! parameters, axis extents, and strides comes from
//! `manifest::shader_params_layout`, the same source used by the manifest.
//!
//! Supports F32 plus quantized loaders through 8/16-bit storage extensions,
//! `SubgroupTree` through `GL_KHR_shader_subgroup_arithmetic`, and fixed
//! `SharedTree` workgroup collectives through GLSL shared storage and barriers.

pub mod addr;
pub mod expr;
pub mod stmts;
pub mod types;

#[cfg(test)]
mod tests;

pub(crate) use addr::{index_expr, view_name};

use rir_core::Access;
use rir_lower::{LoopKernel, MemType};

use crate::EmitError;
use crate::manifest::{shader_params_layout, vulkan_caps};

/// Shader `#extension` directives derived from the same capabilities as the
/// manifest features, avoiding separate manually maintained lists.
fn glsl_extensions(k: &LoopKernel) -> Vec<&'static str> {
    let caps = vulkan_caps(k);
    let mut v = Vec::new();
    if caps.subgroup {
        v.push("GL_KHR_shader_subgroup_arithmetic");
    }
    if caps.f16 {
        v.push("GL_EXT_shader_16bit_storage");
        v.push("GL_EXT_shader_explicit_arithmetic_types_float16");
    }
    if caps.i8 {
        v.push("GL_EXT_shader_8bit_storage");
        v.push("GL_EXT_shader_explicit_arithmetic_types_int8");
    }
    v
}

/// Unsigned division by a runtime divisor, printed only when the lowering
/// flattens its grid.
///
/// The multiplier and the shift are constants of the buffer, precomputed host
/// side by `fastdiv_magic`, so the decomposition of a linear index costs a
/// multiply-high and a shift instead of an integer division per axis. It is the
/// same arithmetic the CUDA emitter prints and the same the oracle judges; the
/// only difference between the three is the spelling of the multiply-high.
const FASTDIV_PRELUDE: &str = r#"// Magic-number division: the divisor's reciprocal is precomputed host side
// and passed in the constant buffer, so the decomposition of a flattened
// index costs a multiply-high instead of an integer division.
uint rir_fastdiv(uint n, uint mp, uint sh) {
    uint hi;
    uint lo;
    umulExtended(n, mp, hi, lo);
    return (hi + n) >> sh;
}
uint rir_fastmod(uint n, uint mp, uint sh, uint d) { return n - rir_fastdiv(n, mp, sh) * d; }
"#;

/// The Vulkan printer: the shared skeleton, with GLSL's lexicon
/// (`crate::printer`, `crate::dialect`).
type VkPrinter<'k> = crate::printer::Printer<'k, crate::dialect::Vulkan>;

pub fn emit_vulkan(k: &LoopKernel) -> Result<String, EmitError> {
    let mut p = VkPrinter::new(k);

    p.line("// Generated by rir-gen - DO NOT EDIT MANUALLY.");
    p.line(&format!(
        "// Kernel: {} (backend vulkan, reduction {}, scan {}, variante {}).",
        k.name,
        k.schedule.reduction().name(),
        k.schedule.scan().name(),
        k.schedule.variant().unwrap_or("repli")
    ));
    p.line(&format!(
        "// Strides are bytes in ggml order; parallel axes are mapped by {}.",
        k.schedule.par_map().name()
    ));
    p.line("#version 450");
    for ext in glsl_extensions(k) {
        p.line(&format!("#extension {ext} : require"));
    }
    p.line("");
    p.line(&format!(
        "layout(local_size_x = {}, local_size_y = {}, local_size_z = {}) in;",
        k.schedule.block()[0],
        k.schedule.block()[1],
        k.schedule.block()[2]
    ));
    // Shared storage, as the kernel declares it:
    // the reduction trees, the staged tiles and the scan's own arrays are one
    // list, and this prints it rather than deriving it from the statements
    // below.
    for (array, len) in &k.shared {
        let name = p.shared(*array);
        p.line(&format!("shared float {name}[{len}];"));
    }
    // Constant tables, derived from the loop nest. One SPIR-V module per
    // variant here, so the plain name is unambiguous - unlike Metal, whose
    // variants share one translation unit.
    for lut in k.luts() {
        let values: Vec<String> = lut.values().iter().map(|v| format!("{v}.0")).collect();
        p.line(&format!(
            "const float {}[{}] = float[]({});",
            lut.symbol(),
            values.len(),
            values.join(", ")
        ));
    }
    p.line("");

    // Declare one buffer per access type present in the body. Lowering has
    // already determined which types are read at each location.
    for (i, (a, tys)) in k.args.iter().zip(k.mem_types()).enumerate() {
        let qualifier = match a.access {
            Access::Read => "readonly ",
            Access::Write => "",
        };
        for ty in &tys {
            let glsl_ty = match ty {
                MemType::F32 => "float",
                MemType::F16 => "float16_t",
                MemType::I8 => "int8_t",
                MemType::U8 => "uint8_t",
            };
            p.line(&format!(
                "layout(std430, binding = {i}) {qualifier}buffer Buf{i}{} {{ {glsl_ty} {}[]; }};",
                ty.view_suffix(),
                view_name(&a.name, *ty)
            ));
        }
    }
    p.line("");

    p.line("layout(push_constant) uniform PC {");
    for (name, ty) in shader_params_layout(k) {
        p.line(&format!("    {ty} {name};"));
    }
    p.line("} pc;");
    p.line("");
    // Read off the loop nest, not off the schedule: what has to be declared is
    // what the body uses.
    // Not `flat_axes` alone: a linear-addressing variant is flattened and
    // divides nothing, so the prelude would be two
    // functions no line of the kernel calls.
    if !k.flat_axes().is_empty() && !k.linear_addr() {
        p.out.push_str(FASTDIV_PRELUDE);
    }

    p.line("void main() {");
    p.indent = 1;
    let body = k.body.clone();
    p.stmts(&body)?;
    p.indent = 0;
    p.line("}");

    Ok(p.out)
}
