//! Metal emitter: Loop IR to Metal Shading Language (`kernel.metal`).
//!
//! The emitter is deliberately a syntax printer. Schedules select the
//! thread/threadgroup mapping and lowering selects the reduction strategy.
//! Buffer addresses remain byte-based, matching `ggml_tensor.nb[]` directly.

pub mod addr;
pub mod expr;
pub mod stmts;
pub mod types;

#[cfg(test)]
mod tests;

use rir_core::Access;
use rir_lower::LoopKernel;

use crate::EmitError;

use crate::manifest::shader_params_layout;

/// The Metal printer: the shared skeleton, with MSL's lexicon
/// (`crate::printer`, `crate::dialect`).
type MetalPrinter<'k> = crate::printer::Printer<'k, crate::dialect::Metal>;

/// Unsigned division by a runtime divisor, printed only when the lowering
/// flattens its grid.
///
/// The multiplier and the shift are constants of the buffer, precomputed host
/// side by `fastdiv_magic`, so the decomposition of a linear index costs a
/// multiply-high and a shift instead of an integer division per axis. It is the
/// same arithmetic the CUDA emitter prints and the same the oracle judges; the
/// only difference between the three is the spelling of the multiply-high.
const FASTDIV_PRELUDE: &str = r#"// Magic-number division: the divisor's reciprocal is precomputed host side
// and passed in the constant buffer, so the decomposition of a flattened
// index costs a multiply-high instead of an integer division.
#ifndef RIR_FASTDIV
#define RIR_FASTDIV
inline uint rir_fastdiv(uint n, uint mp, uint sh) { return (mulhi(n, mp) + n) >> sh; }
inline uint rir_fastmod(uint n, uint mp, uint sh, uint d) { return n - rir_fastdiv(n, mp, sh) * d; }
#endif
"#;

pub fn emit_metal(k: &LoopKernel) -> Result<String, EmitError> {
    let mut p = MetalPrinter::new(k);

    p.line("// Generated by rir-gen - DO NOT EDIT MANUALLY.");
    let artifact = crate::manifest::artifact_name(k);
    p.line(&format!(
        "// Kernel: {} (backend metal, reduction {}, scan {}, variante {}).",
        k.name,
        k.schedule.reduction().name(),
        k.schedule.scan().name(),
        k.schedule.variant().unwrap_or("repli")
    ));
    p.line(&format!(
        "// Strides are bytes in ggml order; parallel axes are mapped by {}.",
        k.schedule.par_map().name()
    ));
    p.line("#include <metal_stdlib>");
    p.line("using namespace metal;");
    p.line("");
    // One params struct *per artifact*: every RIR variant is inlined into
    // ggml's single Metal library source, so both the struct and the entrypoint
    // carry the artifact name - the kernel's for a pair's fallback, and the
    // kernel plus the variant otherwise. Naming them after the kernel alone
    // would have two lowerings of one kernel redefine the same struct in that
    // single translation unit.
    for lut in k.luts() {
        let values: Vec<String> = lut.values().iter().map(|v| format!("{v}.0f")).collect();
        p.line(&format!(
            "constant float rir_{artifact}_{}[{}] = {{{}}};",
            lut.symbol(),
            values.len(),
            values.join(", ")
        ));
        p.line("");
    }
    p.line(&format!("struct rir_{artifact}_params {{"));
    for (name, ty) in shader_params_layout(k) {
        p.line(&format!("    {ty} {name};"));
    }
    p.line("};");
    p.line("");
    // Read off the loop nest, not off the schedule: what has to be declared is
    // what the body uses. The names carry no artifact prefix - the two
    // functions are identical wherever they appear - but Metal concatenates
    // every RIR variant into one translation unit, so two flattened artifacts
    // would define them twice. An include guard is the answer the language
    // already has, and it is why this is the one prelude that carries one.
    // Not `flat_axes` alone: a linear-addressing variant is flattened and
    // divides nothing, so the prelude would be two
    // functions no line of the kernel calls.
    if !k.flat_axes().is_empty() && !k.linear_addr() {
        p.out.push_str(FASTDIV_PRELUDE);
    }
    p.line(&format!("kernel void {}(", crate::manifest::entrypoint(k)));
    p.indent = 1;
    for (i, arg) in k.args.iter().enumerate() {
        let qualifier = match arg.access {
            Access::Read => "device const uchar*",
            Access::Write => "device uchar*",
        };
        p.line(&format!("{qualifier} {} [[buffer({i})]],", arg.name));
    }
    p.line(&format!(
        "constant rir_{artifact}_params& pc [[buffer({})]],",
        k.args.len()
    ));
    p.line("uint3 group_id [[threadgroup_position_in_grid]],");
    p.line("uint3 global_id [[thread_position_in_grid]],");
    if k.uses_shared() {
        p.line("uint threadgroup_lane_id [[thread_index_in_threadgroup]])");
    } else {
        p.line("uint simd_lane_id [[thread_index_in_simdgroup]])");
    }
    p.indent = 0;
    p.line("{");
    p.indent = 1;
    // Threadgroup storage, as the kernel declares it: the reduction trees, the
    // staged tiles, and the scan's own arrays are
    // one list, and this prints it rather than deriving it from the statements
    // below.
    for (array, len) in &k.shared {
        let name = p.shared(*array);
        p.line(&format!("threadgroup float {name}[{len}];"));
    }
    let body = k.body.clone();
    p.stmts(&body)?;
    p.indent = 0;
    p.line("}");
    Ok(p.out)
}
