//! CUDA device and kernel, built **from the manifest** - the short measurement
//! loop's second backend.
//!
//! The carrier is the cheap one the plan recommends: **compile on the fly and
//! load**. A generated `.cu` already contains its `extern "C"` launch stub
//!, so what this module adds is a fixed host harness - allocate, upload,
//! download, synchronize - compiled once per process, and one shared object per
//! kernel compiled by the same `nvcc` the fork uses, with the same
//! `-use_fast_math`. Linking NVRTC and the driver API into this crate
//! would have bought nothing: the harness needs `cudaMalloc`, `cudaMemcpy` and a
//! launch, the compiler is already a build dependency of the fork, and a missing
//! toolkit has to stay a **recoverable** error - the same property the dynamic
//! loading of `libvulkan` has.
//!
//! The interface is deliberately the Vulkan one: `Gpu::open`, `Gpu::build`,
//! `Pipeline::prepare`, `Session::dispatch`/`time`/`read_outputs`. That is what
//! makes `device_parity` and `device_timing` parameterizable by backend instead
//! of duplicated, and it is why the checks above the device - binding count,
//! direction, addressed range, constant block, grid - live on `Manifest` and are
//! called from both halves.

use std::cell::Cell;
use std::ffi::{CString, OsString, c_char, c_void};
use std::path::{Path, PathBuf};
use std::sync::OnceLock;
use std::sync::atomic::{AtomicU64, Ordering};

use libloading::{Library, Symbol};

use crate::manifest::{BoundArg, Manifest, ManifestDispatch, ManifestReader};
use crate::{Arg, RuntimeError, Values};

/// The host half, compiled once per process. Everything a dispatch needs from
/// the CUDA runtime API and nothing else - this crate validates results, not
/// throughput, so there is no stream, no pinned memory and no pool.
const HARNESS: &str = r#"// Generated by rir-runtime - the host half of the short loop.
#include <cuda_runtime.h>
#include <cstdio>

extern "C" int rir_rt_device_count() {
    int n = 0;
    return cudaGetDeviceCount(&n) == cudaSuccess ? n : 0;
}
extern "C" int rir_rt_device_name(char * buf, int len) {
    cudaDeviceProp prop;
    if (cudaGetDeviceProperties(&prop, 0) != cudaSuccess) { return 0; }
    std::snprintf(buf, len, "%s", prop.name);
    return 1;
}
extern "C" size_t rir_rt_shared_per_block() {
    cudaDeviceProp prop;
    if (cudaGetDeviceProperties(&prop, 0) != cudaSuccess) { return 0; }
    return prop.sharedMemPerBlock;
}
// The two other budgets the manifest publishes.
// A compute capability is reported the way the manifest spells it: major·10 +
// minor, so `cuda>=5.3` compares as 53.
extern "C" int rir_rt_compute_capability() {
    cudaDeviceProp prop;
    if (cudaGetDeviceProperties(&prop, 0) != cudaSuccess) { return 0; }
    return prop.major * 10 + prop.minor;
}
extern "C" int rir_rt_max_threads_per_block() {
    cudaDeviceProp prop;
    if (cudaGetDeviceProperties(&prop, 0) != cudaSuccess) { return 0; }
    return prop.maxThreadsPerBlock;
}
extern "C" void * rir_rt_alloc(size_t n) {
    void * p = nullptr;
    return cudaMalloc(&p, n) == cudaSuccess ? p : nullptr;
}
extern "C" void rir_rt_free(void * p) { cudaFree(p); }
extern "C" int rir_rt_upload(void * dst, const void * src, size_t n) {
    return cudaMemcpy(dst, src, n, cudaMemcpyHostToDevice) == cudaSuccess;
}
extern "C" int rir_rt_download(void * dst, const void * src, size_t n) {
    return cudaMemcpy(dst, src, n, cudaMemcpyDeviceToHost) == cudaSuccess;
}
// Synchronize and report. The launch itself is asynchronous and reports nothing,
// so this is where an invalid geometry or an out-of-bounds access surfaces,
// which is why every dispatch ends here rather than at the launch.
extern "C" int rir_rt_sync(char * buf, int len) {
    cudaError_t e = cudaDeviceSynchronize();
    if (e == cudaSuccess) { e = cudaGetLastError(); }
    if (e == cudaSuccess) { return 1; }
    std::snprintf(buf, len, "%s", cudaGetErrorString(e));
    return 0;
}
"#;

type FnCount = unsafe extern "C" fn() -> i32;
type FnName = unsafe extern "C" fn(*mut c_char, i32) -> i32;
type FnShared = unsafe extern "C" fn() -> usize;
type FnLimit = unsafe extern "C" fn() -> i32;
type FnAlloc = unsafe extern "C" fn(usize) -> *mut c_void;
type FnFree = unsafe extern "C" fn(*mut c_void);
type FnCopy = unsafe extern "C" fn(*mut c_void, *const c_void, usize) -> i32;
type FnSync = unsafe extern "C" fn(*mut c_char, i32) -> i32;

/// The generated stub's signature. The stream is a
/// `void *`: this loop runs on the default stream, and the fork's adapter is
/// the caller that has one to pass.
type FnLaunch = unsafe extern "C" fn(*const *mut c_void, *const c_void, *const u32, *mut c_void);

/// A generated CUDA translation unit, and what it needs to compile.
///
/// The params header is supplied by the caller rather than found: a `.cu`
/// includes `"../../ggml-rir/rir_kernel_params.h"`, which is where it sits in
/// the fork, and this crate has no business knowing a path inside the
/// repository.
pub struct Unit<'a> {
    /// `rir_launch_<artifact>` is the symbol resolved from the shared object.
    pub artifact: &'a str,
    /// The `.cu` as the generator wrote it, byte for byte.
    pub source: &'a str,
    /// `rir_kernel_params.h` as the generator wrote it.
    pub params_header: &'a str,
}

/// The `nvcc` invocation this machine accepts, probed once.
///
/// The probe exists for one reason and it is not portability theatre: a toolkit
/// refusing the system `gcc` is a property of the box (this one needs
/// `-ccbin g++-15`, `memory/gpu-lanes-on-this-box`), and hardcoding it would
/// make the CUDA lane run here and skip everywhere else.
fn nvcc_flags() -> Result<&'static Vec<String>, &'static RuntimeError> {
    static FLAGS: OnceLock<Result<Vec<String>, RuntimeError>> = OnceLock::new();
    FLAGS.get_or_init(probe_nvcc).as_ref()
}

/// CUDA's standard compiler override, shared with CMake and the FFI build.
fn nvcc() -> OsString {
    std::env::var_os("CUDACXX")
        .filter(|compiler| !compiler.is_empty())
        .unwrap_or_else(|| OsString::from("nvcc"))
}

fn probe_nvcc() -> Result<Vec<String>, RuntimeError> {
    if std::process::Command::new(nvcc())
        .arg("--version")
        .output()
        .is_err()
    {
        return Err(RuntimeError::NoToolkit(
            "CUDA compiler unavailable (set CUDACXX or put nvcc in PATH)".into(),
        ));
    }
    let dir = std::env::temp_dir().join(format!("rir-cuda-probe-{}", std::process::id()));
    std::fs::create_dir_all(&dir)?;
    let probe = dir.join("probe.cu");
    std::fs::write(&probe, "__global__ void rir_probe() {}\n")?;

    // The fork's own flags first (`ggml-cuda/CMakeLists.txt`): a kernel measured
    // here must be the kernel the fork ships.
    let mut base: Vec<String> = vec!["-use_fast_math".into()];
    if let Some(arch) = std::env::var_os("RIR_CUDA_ARCH") {
        base.push(format!("-arch={}", arch.to_string_lossy()));
    }
    let mut last = String::new();
    let found = std::env::var("RIR_NVCC_CCBIN")
        .ok()
        .into_iter()
        .map(|c| vec![c])
        .chain([vec![], vec!["g++-15".into()], vec!["g++-14".into()]])
        .find_map(|ccbin| {
            let mut flags = base.clone();
            for c in &ccbin {
                flags.push("-ccbin".into());
                flags.push(c.clone());
            }
            let out = std::process::Command::new(nvcc())
                .args(&flags)
                .arg("-c")
                .arg(&probe)
                .arg("-o")
                .arg(dir.join("probe.o"))
                .output();
            match out {
                Ok(o) if o.status.success() => Some(flags),
                Ok(o) => {
                    last = String::from_utf8_lossy(&o.stderr).into_owned();
                    None
                }
                Err(e) => {
                    last = e.to_string();
                    None
                }
            }
        });
    let _ = std::fs::remove_dir_all(&dir);
    found.ok_or_else(|| {
        RuntimeError::NoToolkit(format!(
            "nvcc compiles nothing here (set RIR_NVCC_CCBIN): {}",
            last.lines().next().unwrap_or("")
        ))
    })
}

/// A compute capability written `major.minor`, as major·10 + minor.
///
/// `None` rather than a default for anything else, so a feature this runtime
/// cannot read is refused instead of compared against a zero that every device
/// satisfies.
fn compute_capability(spelling: &str) -> Option<u32> {
    let (major, minor) = spelling.split_once('.')?;
    let (major, minor) = (major.parse::<u32>().ok()?, minor.parse::<u32>().ok()?);
    // A CUDA minor version is a single digit, and the packed form assumes it:
    // `5.10` would collide with `6.0`.
    (minor < 10).then_some(major * 10 + minor)
}

/// The toolkit could not be used at all: no `nvcc`, a compiler that did not
/// start, an object that would not load. Three unrelated error types, one
/// class of failure, so the variant carries the cause as text.
fn no_toolkit(error: impl std::fmt::Display) -> RuntimeError {
    RuntimeError::NoToolkit(error.to_string())
}

/// Compiles one translation unit into a shared object and loads it.
fn compile_and_load(dir: &Path, unit: &str, source: &str) -> Result<Library, RuntimeError> {
    let flags = nvcc_flags().map_err(no_toolkit)?;
    let cu = dir.join(format!("{unit}.cu"));
    let so = dir.join(format!("lib{unit}.so"));
    std::fs::write(&cu, source)?;
    let out = std::process::Command::new(nvcc())
        .args(flags)
        // `-cudart shared` so every object this process loads shares one CUDA
        // runtime, hence one primary context: the harness allocates and the
        // kernel's own object launches, and a static runtime in each would give
        // them two device heaps.
        .args(["-shared", "-cudart", "shared", "-Xcompiler", "-fPIC"])
        .arg(&cu)
        .arg("-o")
        .arg(&so)
        .output()
        .map_err(no_toolkit)?;
    if !out.status.success() {
        return Err(RuntimeError::Compile(
            String::from_utf8_lossy(&out.stderr).into_owned(),
        ));
    }
    // SAFETY: the object was just produced by `nvcc` from source this process
    // wrote, in a directory named after this process. Loading it runs the CUDA
    // runtime's own initializers and nothing else.
    unsafe { Library::new(&so) }.map_err(no_toolkit)
}

/// A symbol resolved out of a loaded object, held for the object's lifetime.
///
/// `Symbol` borrows its library, and both live in the same struct here, so the
/// pointer is taken raw. It is only ever called through the owner, which drops
/// the library last.
unsafe fn symbol<T: Copy>(lib: &Library, name: &str) -> Result<T, RuntimeError> {
    let c = CString::new(name).expect("a symbol name has no interior nul");
    let sym: Symbol<T> =
        unsafe { lib.get(c.as_bytes_with_nul()) }.map_err(|e| RuntimeError::MissingSymbol {
            name: name.to_string(),
            detail: e.to_string(),
        })?;
    Ok(*sym)
}

/// Serial number of the next `Gpu` opened by this process.
///
/// The working directory has to be unique **per instance**, not per process, and
/// that is not a precaution: `cargo test` runs its tests on threads of one
/// process, several of them open a `Gpu`, and every instance compiles a harness
/// under the name `rir_rt_harness`. Sharing the directory made two `nvcc`
/// invocations write one shared object, and made the first `Drop` remove a
/// directory the others were still building in.
static INSTANCES: AtomicU64 = AtomicU64::new(0);

/// The device, and the host half of the loop.
pub struct Gpu {
    name: String,
    /// The three budgets the manifest publishes, read
    /// once at open: shared memory per block, threads per block, and compute
    /// capability as major·10 + minor.
    shared_per_block: usize,
    max_threads_per_block: u32,
    compute_capability: u32,
    alloc: FnAlloc,
    free: FnFree,
    upload: FnCopy,
    download: FnCopy,
    sync: FnSync,
    /// Dropped last: every pointer above lives in it.
    _harness: Library,
    dir: PathBuf,
    /// Serial number of the next kernel built here, so two builds of one
    /// artifact on one device do not share a directory either.
    builds: AtomicU64,
}

impl Gpu {
    /// Compiles the harness, loads it, and checks there is a device.
    ///
    /// Every failure is typed and recoverable: no toolkit (`NoToolkit`), no GPU
    /// (`NoDevice`). A caller therefore knows *why* it skips, which is the
    /// property the Vulkan half has and the reason it is worth having here.
    pub fn open() -> Result<Gpu, RuntimeError> {
        let dir = std::env::temp_dir().join(format!(
            "rir-cuda-{}-{}",
            std::process::id(),
            INSTANCES.fetch_add(1, Ordering::Relaxed)
        ));
        std::fs::create_dir_all(&dir)?;
        let harness = compile_and_load(&dir, "rir_rt_harness", HARNESS)?;
        // SAFETY: the symbols below are the ones `HARNESS` defines, with the
        // signatures written next to them.
        let (count, name_of, shared, threads, cc, alloc, free, upload, download, sync) = unsafe {
            (
                symbol::<FnCount>(&harness, "rir_rt_device_count")?,
                symbol::<FnName>(&harness, "rir_rt_device_name")?,
                symbol::<FnShared>(&harness, "rir_rt_shared_per_block")?,
                symbol::<FnLimit>(&harness, "rir_rt_max_threads_per_block")?,
                symbol::<FnLimit>(&harness, "rir_rt_compute_capability")?,
                symbol::<FnAlloc>(&harness, "rir_rt_alloc")?,
                symbol::<FnFree>(&harness, "rir_rt_free")?,
                symbol::<FnCopy>(&harness, "rir_rt_upload")?,
                symbol::<FnCopy>(&harness, "rir_rt_download")?,
                symbol::<FnSync>(&harness, "rir_rt_sync")?,
            )
        };
        // SAFETY: `count` takes nothing and returns a device count.
        if unsafe { count() } == 0 {
            return Err(RuntimeError::NoDevice);
        }
        let mut buf = [0i8; 256];
        // SAFETY: `name_of` writes at most `len` bytes into `buf`, nul-terminated.
        let name = unsafe {
            if name_of(buf.as_mut_ptr(), buf.len() as i32) == 1 {
                std::ffi::CStr::from_ptr(buf.as_ptr())
                    .to_string_lossy()
                    .into_owned()
            } else {
                "CUDA device".to_string()
            }
        };
        // SAFETY: same contract, no arguments.
        let (shared_per_block, max_threads_per_block, compute_capability) =
            unsafe { (shared(), threads().max(0) as u32, cc().max(0) as u32) };
        Ok(Gpu {
            name,
            shared_per_block,
            max_threads_per_block,
            compute_capability,
            alloc,
            free,
            upload,
            download,
            sync,
            _harness: harness,
            dir,
            builds: AtomicU64::new(0),
        })
    }

    pub fn name(&self) -> &str {
        &self.name
    }

    /// Static shared memory a block may use. One of the three device budgets the
    /// manifest publishes, and one of the facts left to
    /// be checked here - the two left to the fork's adapter instead are the grid
    /// bound and pointer alignment, neither of which this loop can see.
    pub fn shared_per_block(&self) -> usize {
        self.shared_per_block
    }

    /// Threads one block may hold.
    pub fn max_threads_per_block(&self) -> u32 {
        self.max_threads_per_block
    }

    /// Compute capability as the manifest spells it: major·10 + minor, so 8.9 is
    /// 89 and `cuda>=5.3` compares as 53.
    pub fn compute_capability(&self) -> u32 {
        self.compute_capability
    }

    /// Checks manifest features **before** compiling anything, exactly as the
    /// Vulkan half checks them before creating anything.
    ///
    /// Two properties matter here and only one of them is about a device. The
    /// first: an insufficient device produces `MissingFeature`, naming what it
    /// lacks, instead of an `nvcc` diagnostic or a launch failure about a
    /// resource. The second, and it is the one worth the code: **an unknown
    /// feature is a rejection, not a shrug**. A manifest newer than this runtime
    /// carries a requirement this runtime does not know how to satisfy, and
    /// running it anyway is how a lane starts reporting a green measurement for
    /// a kernel whose contract was never evaluated.
    pub fn check_features(&self, m: &Manifest) -> Result<(), RuntimeError> {
        for f in &m.features {
            // A published bound is always "the device must provide at least
            // this", so every arm reads the same way: parse the number the
            // feature carries, compare it against what the device reports, and
            // treat an unreadable number as a refusal rather than as zero.
            let (ok, detail) = if let Some(v) = f.strip_prefix("cuda>=") {
                match compute_capability(v) {
                    Some(need) => (
                        self.compute_capability >= need,
                        format!(
                            "device at {}.{}",
                            self.compute_capability / 10,
                            self.compute_capability % 10
                        ),
                    ),
                    None => (false, "unreadable compute capability".into()),
                }
            } else if let Some(v) = f.strip_prefix("shared_bytes>=") {
                match v.parse::<usize>() {
                    Ok(need) => (
                        need <= self.shared_per_block,
                        format!("{} bytes of shared memory per block", self.shared_per_block),
                    ),
                    Err(_) => (false, "unreadable byte count".into()),
                }
            } else if let Some(v) = f.strip_prefix("block_threads>=") {
                match v.parse::<u32>() {
                    Ok(need) => (
                        need <= self.max_threads_per_block,
                        format!("{} threads per block", self.max_threads_per_block),
                    ),
                    Err(_) => (false, "unreadable thread count".into()),
                }
            } else {
                (false, "feature unknown to this runtime".into())
            };
            if !ok {
                return Err(RuntimeError::MissingFeature {
                    feature: f.clone(),
                    detail,
                });
            }
        }
        Ok(())
    }

    /// Compiles a generated `.cu` and resolves its launch stub.
    ///
    /// The temporary directory reproduces the fork's layout - the unit under
    /// `ggml-cuda/rir/`, the params header under `ggml-rir/` - because the
    /// generated include says so. Compiling it flat would be compiling a
    /// different file.
    pub fn build(
        &self,
        manifest: &Manifest,
        unit: &Unit<'_>,
    ) -> Result<Pipeline<'_>, RuntimeError> {
        if manifest.backend != "cuda" {
            return Err(RuntimeError::BadManifest(format!(
                "backend '{}': this pipeline executes cuda",
                manifest.backend
            )));
        }
        self.check_features(manifest)?;

        // The serial number, and not the artifact alone: nothing forbids
        // building one artifact twice on one device, and two builds sharing a
        // directory would have one `nvcc` overwrite the other's source.
        let dir = self.dir.join(format!(
            "build-{}-{}",
            self.builds.fetch_add(1, Ordering::Relaxed),
            unit.artifact
        ));
        let rir = dir.join("ggml-cuda/rir");
        let params = dir.join("ggml-rir");
        std::fs::create_dir_all(&rir)?;
        std::fs::create_dir_all(&params)?;
        std::fs::write(params.join("rir_kernel_params.h"), unit.params_header)?;
        let lib = compile_and_load(&rir, &format!("rir_{}", unit.artifact), unit.source)?;
        // SAFETY: the stub is `extern "C"` with the signature of `FnLaunch`,
        // generated from the same `LoopKernel` as the manifest.
        let launch = unsafe { symbol::<FnLaunch>(&lib, &format!("rir_launch_{}", unit.artifact))? };
        Ok(Pipeline {
            gpu: self,
            manifest: manifest.clone(),
            launch,
            _lib: lib,
        })
    }

    fn sync(&self) -> Result<(), RuntimeError> {
        let mut buf = [0i8; 256];
        // SAFETY: `sync` writes at most `len` bytes into `buf`, nul-terminated,
        // and returns 1 on success.
        let ok = unsafe { (self.sync)(buf.as_mut_ptr(), buf.len() as i32) } == 1;
        if ok {
            return Ok(());
        }
        // SAFETY: on failure the harness wrote a nul-terminated message.
        let detail = unsafe {
            std::ffi::CStr::from_ptr(buf.as_ptr())
                .to_string_lossy()
                .into_owned()
        };
        Err(RuntimeError::Cuda {
            op: "cudaDeviceSynchronize",
            detail,
        })
    }
}

impl Drop for Gpu {
    fn drop(&mut self) {
        // The sources and objects this process compiled. Failing to remove them
        // is not an error worth propagating out of a destructor.
        let _ = std::fs::remove_dir_all(&self.dir);
    }
}

/// A device allocation, freed through the harness that made it.
struct Buffer {
    ptr: *mut c_void,
    free: FnFree,
}

impl Drop for Buffer {
    fn drop(&mut self) {
        if !self.ptr.is_null() {
            // SAFETY: the pointer came from `rir_rt_alloc` and is freed once.
            unsafe { (self.free)(self.ptr) };
        }
    }
}

/// A kernel, reusable across `run` calls.
pub struct Pipeline<'g> {
    gpu: &'g Gpu,
    manifest: Manifest,
    launch: FnLaunch,
    /// Dropped last: `launch` points into it.
    _lib: Library,
}

impl Pipeline<'_> {
    pub fn manifest(&self) -> &Manifest {
        &self.manifest
    }

    /// A complete dispatch: upload inputs, execute, read outputs back into bound
    /// slices. Synchronous.
    pub fn run(&self, args: &mut [Arg], values: &Values) -> Result<(), RuntimeError> {
        let session = self.prepare(args, values)?;
        session.dispatch()?;
        session.read_outputs(args)
    }

    /// The first half of `run`: checks, allocation, upload, and resolution of
    /// grid and params. Its result can be dispatched any number of times without
    /// touching host memory - which is what makes `Session::time` measurable.
    pub fn prepare(&self, args: &[Arg], values: &Values) -> Result<Session<'_>, RuntimeError> {
        let (params, grid) = self.manifest.encode_dispatch(args, values)?;

        let mut buffers = Vec::with_capacity(args.len());
        for a in args.iter() {
            // A zero-length argument stays legal for the kernel - no thread will
            // read it - but `cudaMalloc(0)` returns nothing to bind.
            let len = a.len().max(4);
            // SAFETY: the harness returns a device pointer or null.
            let ptr = unsafe { (self.gpu.alloc)(len) };
            if ptr.is_null() {
                return Err(RuntimeError::Cuda {
                    op: "cudaMalloc",
                    detail: format!("{len} bytes"),
                });
            }
            buffers.push(Buffer {
                ptr,
                free: self.gpu.free,
            });
        }
        for (b, a) in buffers.iter().zip(args.iter()) {
            if let Arg::In(data) = a
                && !data.is_empty()
            {
                // SAFETY: `data` is `data.len()` readable bytes and `b.ptr` a
                // device allocation of at least that size.
                let ok = unsafe { (self.gpu.upload)(b.ptr, data.as_ptr().cast(), data.len()) };
                if ok != 1 {
                    return Err(RuntimeError::Cuda {
                        op: "cudaMemcpy(HostToDevice)",
                        detail: format!("{} bytes", data.len()),
                    });
                }
            }
        }

        let bound = args
            .iter()
            .map(|a| BoundArg {
                write: matches!(a, Arg::Out(_)),
                len: a.len(),
            })
            .collect();
        Ok(Session {
            pipeline: self,
            pointers: buffers.iter().map(|b| b.ptr).collect(),
            buffers,
            bound,
            params,
            grid,
            in_flight: Cell::new(false),
        })
    }
}

/// A **prepared** dispatch: buffers allocated, inputs uploaded, grid and params
/// resolved. Repeating it measures the kernel and the launch rather than copies.
pub struct Session<'p> {
    pipeline: &'p Pipeline<'p>,
    buffers: Vec<Buffer>,
    /// The same pointers, in binding order, as the stub expects them.
    pointers: Vec<*mut c_void>,
    bound: Vec<BoundArg>,
    params: Vec<u8>,
    grid: [u32; 3],
    /// A dispatch that never returned leaves the device holding these buffers.
    in_flight: Cell<bool>,
}

impl Session<'_> {
    /// Number of blocks the manifest derives from the params - needed to
    /// interpret a timing result.
    pub fn groups(&self) -> [u32; 3] {
        self.grid
    }

    /// Submits the dispatch and waits for completion. Reusable.
    pub fn dispatch(&self) -> Result<(), RuntimeError> {
        self.dispatch_n(1)
    }

    /// `n` executions on the default stream, then one synchronization.
    ///
    /// They serialize because they are on one stream, so `n` executions cost `n`
    /// times one - the same property the Vulkan half gets from a memory barrier
    /// between its recorded dispatches, and the reason a timing here is
    /// comparable to a timing there.
    pub(crate) fn dispatch_n(&self, n: u32) -> Result<(), RuntimeError> {
        if self.in_flight.get() {
            return Err(RuntimeError::InFlight);
        }
        for _ in 0..n.max(1) {
            // SAFETY: `pointers` has one device pointer per binding in the order
            // the stub reads them, `params` is exactly the byte layout the
            // generated `static_assert` pins, and `grid` is three `u32`. The
            // stream is the default one.
            unsafe {
                (self.pipeline.launch)(
                    self.pointers.as_ptr(),
                    self.params.as_ptr().cast(),
                    self.grid.as_ptr(),
                    std::ptr::null_mut(),
                );
            }
        }
        // The launch is asynchronous and reports nothing: an invalid geometry or
        // an out-of-bounds access surfaces here.
        self.pipeline.gpu.sync().inspect_err(|_| {
            // The device is in an unknown state; nothing it may still be reading
            // can be freed.
            self.in_flight.set(true);
        })
    }

    /// Copies output buffers back into bound slices. `args` must be the set used
    /// by `prepare` - same bindings, directions and sizes, **checked**.
    pub fn read_outputs(&self, args: &mut [Arg]) -> Result<(), RuntimeError> {
        self.pipeline.manifest.check_read_back(&self.bound, args)?;
        for (b, a) in self.buffers.iter().zip(args.iter_mut()) {
            if let Arg::Out(data) = a
                && !data.is_empty()
            {
                // SAFETY: `data` is `data.len()` writable bytes and `b.ptr` a
                // device allocation of at least that size, sized by `prepare`
                // from this very slice.
                let ok = unsafe {
                    (self.pipeline.gpu.download)(data.as_mut_ptr().cast(), b.ptr, data.len())
                };
                if ok != 1 {
                    return Err(RuntimeError::Cuda {
                        op: "cudaMemcpy(DeviceToHost)",
                        detail: format!("{} bytes", data.len()),
                    });
                }
            }
        }
        Ok(())
    }

    /// Times `iters` dispatches and returns the **mean** per dispatch after
    /// uncounted `warmup` runs - lazy module loading and clock ramp are paid
    /// once, not on every measurement.
    ///
    /// All `iters` launches precede a single synchronization, so the fixed host
    /// cost is divided by `iters` instead of paid each run. What remains
    /// included is `1/iters` of that constant; the rest is the kernel.
    pub fn time(&self, warmup: u32, iters: u32) -> Result<std::time::Duration, RuntimeError> {
        if warmup > 0 {
            self.dispatch_n(warmup)?;
        }
        let iters = iters.max(1);
        let start = std::time::Instant::now();
        self.dispatch_n(iters)?;
        Ok(start.elapsed() / iters)
    }

    /// The same measurement, named as the Vulkan half names its unbarriered
    /// one, and identical to `time` here on purpose: launches on one stream
    /// serialize without an object between them, so there is no barrier to
    /// remove and nothing to overlap. The pair exists so `AnySession` has one
    /// shape, not because CUDA has two numbers.
    pub fn time_stream(
        &self,
        warmup: u32,
        iters: u32,
    ) -> Result<std::time::Duration, RuntimeError> {
        self.time(warmup, iters)
    }
}

impl Drop for Session<'_> {
    fn drop(&mut self) {
        if self.in_flight.get() {
            // The device did not answer; freeing what it may still read would be
            // a use-after-free on its side. Leak, bounded to the failed dispatch.
            for b in self.buffers.drain(..) {
                std::mem::forget(b);
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::compute_capability;

    /// The spellings the manifest emits, and the ones it must never be read as.
    ///
    /// The packed form is what makes the comparison a single integer, and it is
    /// only sound while a minor version is one digit - so `5.10` is refused
    /// rather than folded onto `6.0`, which would silently accept a device two
    /// generations too old.
    #[test]
    fn a_compute_capability_is_read_as_the_manifest_spells_it() {
        assert_eq!(compute_capability("5.0"), Some(50));
        assert_eq!(compute_capability("5.3"), Some(53));
        assert_eq!(compute_capability("8.9"), Some(89));
        assert_eq!(compute_capability("12.0"), Some(120));
        assert!(compute_capability("8.9") > compute_capability("5.3"));

        // Unreadable is `None`, never a zero every device satisfies.
        assert_eq!(compute_capability("5"), None);
        assert_eq!(compute_capability("5.10"), None);
        assert_eq!(compute_capability(""), None);
        assert_eq!(compute_capability("x.y"), None);
        assert_eq!(compute_capability("5.3.1"), None);
    }
}
