//! AOT C/C++ registry emitter (ADR-4 section 4).
//!
//! Emits `rir_registry.h` / `rir_registry.cpp`: POD structures a ggml backend
//! consumes with no JSON parsing, no allocation and no string comparison in
//! the hot path. Names stay available for diagnostics; the `GGML_OP_*` string
//! is resolved to the enum value **once** by the backend adapter at init.
//!
//! The registry and the JSON manifests are two outputs of the same data - a
//! test rebuilds one from the other and fails on drift.

use rir_lower::LoopKernel;

use crate::integration::{ArgSource, BackendPolicy, GgmlBackend, IntegrationSpec};
use crate::manifest::{entrypoint, ggml_backend, shader_params_layout, variant_id};

pub mod header;

pub use header::emit_params_header;

pub(crate) use header::{REGISTRY_HEADER, max_rank};

/// A registry rule that the declared tables do not satisfy.
///
/// These properties are a typed error, propagated like lowering and emission
/// errors. Invalid tables therefore fail consistently in generation and tests.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[error("{subject}: {detail}")]
pub struct RegistryError {
    /// The kernel, op, or op/backend pair at fault.
    pub subject: String,
    pub detail: String,
}

impl RegistryError {
    fn new(subject: impl Into<String>, detail: impl Into<String>) -> Self {
        RegistryError {
            subject: subject.into(),
            detail: detail.into(),
        }
    }
}

/// Fixed capacities of the POD arrays. Growing them is an ABI change for the
/// registry consumers, hence explicit constants mirrored in the header.
const MAX_BINDINGS: usize = 4;
const MAX_PARAMS: usize = 2;
/// Nine axes cover the four tensor dimensions, four more for a kernel that
/// folds every dimension of a repeated operand (one extra axis per folded
/// dimension), and one more axis used by the dispatch contract.
const MAX_AXES: usize = 9;
const MAX_SHAPE_RULES: usize = 2;

fn backend_enum(b: GgmlBackend) -> &'static str {
    match b {
        GgmlBackend::Cuda => "RIR_BACKEND_CUDA",
        GgmlBackend::Vulkan => "RIR_BACKEND_VULKAN",
        GgmlBackend::Metal => "RIR_BACKEND_METAL",
        GgmlBackend::Cpu => "RIR_BACKEND_CPU",
    }
}

fn policy_enum(p: BackendPolicy) -> &'static str {
    match p {
        BackendPolicy::NativeOnly => "RIR_POLICY_NATIVE_ONLY",
        BackendPolicy::ObserveGenerated => "RIR_POLICY_OBSERVE_GENERATED",
        BackendPolicy::PreferGenerated => "RIR_POLICY_PREFER_GENERATED",
    }
}

/// Emits `(rir_registry.h, rir_registry.cpp)`.
///
/// `variants` are the lowered production GPU kernels with their spec;
/// `specs` is the full integration table (policy rows come from it).
///
/// # Errors
///
/// Returns `RegistryError` whenever a registry property is not satisfied:
/// duplicate variant identity, exceeded POD capacity, spec arity differing from
/// its kernel, unknown axis, or a policy/native-exception contradiction between
/// two kernels for the same op.
pub fn emit_registry(
    variants: &[(&LoopKernel, &IntegrationSpec)],
    specs: &[IntegrationSpec],
) -> Result<(String, String), RegistryError> {
    let mut cpp = String::new();
    cpp.push_str("// Generated by rir-gen - DO NOT EDIT MANUALLY.\n");
    cpp.push_str("#include \"rir_registry.h\"\n\n");

    cpp.push_str("const rir_variant_desc rir_variants[] = {\n");
    // Two variants of one (op, backend) with the same id would be one variant
    // as far as every consumer is concerned - the dispatch-site counters, the
    // lane's "declared but never dispatched" check, telemetry. Asserted here
    // rather than hoped for, because the symptom is a *green* run that counted
    // fifteen kernels as one (ADR-4 section 7).
    {
        let mut seen: Vec<(String, String, u8)> = Vec::new();
        for (k, spec) in variants {
            let Some(op) = spec.ggml_op else { continue };
            let key = (op.to_string(), variant_id(k), ggml_backend(k) as u8);
            if seen.contains(&key) {
                return Err(RegistryError::new(
                    format!("{op}/{}", ggml_backend(k).name()),
                    format!("two variants have identity {}", variant_id(k)),
                ));
            }
            seen.push(key);
        }
    }
    for (k, spec) in variants {
        if !spec.production_on(ggml_backend(k)) {
            return Err(RegistryError::new(
                &k.name,
                "non-production variant in the registry",
            ));
        }
        let Some(op) = spec.ggml_op else {
            return Err(RegistryError::new(
                &k.name,
                "production variant without ggml_op",
            ));
        };
        if k.args.len() > MAX_BINDINGS {
            return Err(RegistryError::new(
                &k.name,
                format!("{} bindings, at most {MAX_BINDINGS}", k.args.len()),
            ));
        }
        if k.params.len() > MAX_PARAMS {
            return Err(RegistryError::new(
                &k.name,
                format!("{} params, at most {MAX_PARAMS}", k.params.len()),
            ));
        }
        // The spec arity is the kernel arity: the two tables are written
        // separately and joined by name, so a mismatch is rejected here - not
        // while indexing two lines below.
        if spec.args.len() != k.args.len() {
            return Err(RegistryError::new(
                &k.name,
                format!(
                    "spec: {} arguments for {} bindings",
                    spec.args.len(),
                    k.args.len()
                ),
            ));
        }
        if spec.params.len() != k.params.len() {
            return Err(RegistryError::new(
                &k.name,
                format!(
                    "spec: {} params for {} kernel params",
                    spec.params.len(),
                    k.params.len()
                ),
            ));
        }

        let mut bindings = Vec::new();
        for (i, a) in k.args.iter().enumerate() {
            let source = match spec.args[i] {
                ArgSource::Src(s) => s as i8,
                ArgSource::Dst => -1,
            };
            let access = match a.access {
                rir_core::Access::Read => "RIR_ACCESS_READ",
                rir_core::Access::Write => "RIR_ACCESS_WRITE",
            };
            bindings.push(format!(
                "{{\"{}\", {}, {}, \"{}\", {}, {}, {}}}",
                a.name,
                source,
                access,
                a.ty.dtype.name(),
                a.ty.rank,
                a.ty.dtype.size_bytes(),
                a.ty.dtype.elements_per_unit()
            ));
        }
        while bindings.len() < MAX_BINDINGS {
            bindings.push("{0, 0, 0, 0, 0, 0, 0}".to_string());
        }

        let mut params = Vec::new();
        for (i, p) in k.params.iter().enumerate() {
            if spec.params[i].name != p.name {
                return Err(RegistryError::new(
                    &k.name,
                    format!(
                        "spec parameter order != kernel: {} instead of {}",
                        spec.params[i].name, p.name
                    ),
                ));
            }
            params.push(format!(
                "{{\"{}\", {}}}",
                p.name, spec.params[i].op_params_offset
            ));
        }
        while params.len() < MAX_PARAMS {
            params.push("{0, 0}".to_string());
        }

        // Axes in push-constant order, each carrying the ggml dimension it
        // indexes on every binding. Read from `arg_axes`, the same field the
        // manifest's `extents` prints, so the two outputs cannot disagree.
        if k.axes.len() > MAX_AXES {
            return Err(RegistryError::new(
                &k.name,
                format!("{} axes, at most {MAX_AXES}", k.axes.len()),
            ));
        }
        let mut axes = Vec::new();
        for (ai, axis) in k.axes.iter().enumerate() {
            let mut dims = Vec::new();
            for b in 0..MAX_BINDINGS {
                let dim = k.arg_axes.get(b).map_or(-1i32, |slots| {
                    slots
                        .iter()
                        .position(|slot| slot.is_some_and(|ax| ax.0 as usize == ai))
                        .map_or(-1, |d| d as i32)
                });
                dims.push(dim.to_string());
            }
            // The fold relation, read off the loop nest's own `IModAxis`
            // instructions rather than declared: the axis that folds *into*
            // this one is the axis a dispatcher must check divides by it.
            let folded = k
                .folds()
                .into_iter()
                .find(|(_, over)| over.0 as usize == ai)
                .map_or(-1i32, |(idx, _)| idx.0 as i32);
            axes.push(format!(
                "{{\"{}\", {{{}}}, {folded}}}",
                axis.name,
                dims.join(", ")
            ));
        }
        while axes.len() < MAX_AXES {
            axes.push("{0, {-1, -1, -1, -1}, -1}".to_string());
        }

        // Grid geometry, by axis index rather than by name: the dispatcher
        // computes ceil(extent / per_workgroup) without replaying lowering.
        let grid = crate::manifest::grid_axes(k);
        if grid.len() > 3 {
            return Err(RegistryError::new(
                &k.name,
                format!("{} grid dimensions, at most three", grid.len()),
            ));
        }
        let mut dispatch = Vec::new();
        for (name, per) in &grid {
            let idx =
                k.axes.iter().position(|a| &a.name == name).ok_or_else(|| {
                    RegistryError::new(&k.name, format!("unknown grid axis {name}"))
                })?;
            dispatch.push(format!("{{{idx}, {per}}}"));
        }
        while dispatch.len() < 3 {
            dispatch.push("{-1, 1}".to_string());
        }

        // The flattened dispatch, published in the same
        // `(axis, per)` shape the grid uses and read by the same host code. A
        // flattened variant has **no** grid axis - `grid_axes` walks
        // `Stmt::Parallel` and there is none - so `dispatch[0]` carries the
        // workgroup width alone, with `axis = -1`: `ggml_rir_grid` reads
        // `n_flat` first and would otherwise dispatch a single block.
        let flat_axes = crate::manifest::flat_axes(k);
        let mut flat = Vec::new();
        for (name, per) in &flat_axes {
            let idx =
                k.axes.iter().position(|a| &a.name == name).ok_or_else(|| {
                    RegistryError::new(&k.name, format!("unknown flat axis {name}"))
                })?;
            flat.push(format!("{{{idx}, {per}}}"));
        }
        if !flat.is_empty() {
            // Points one workgroup covers: the workgroup width under the
            // invocation mapping, one under the workgroup mapping.
            // The same function the grid dimensions use,
            // applied to the single dimension a flattened dispatch has.
            dispatch[0] = format!(
                "{{-1, {}}}",
                k.schedule.par_map().per_workgroup(k.schedule.block(), 0)
            );
        }
        let n_flat = flat.len();
        while flat.len() < MAX_AXES {
            flat.push("{-1, 1}".to_string());
        }

        // Shape rules, with axis *names* resolved to indices into the axes table
        // above. The name is what the schedule table writes and what a reader
        // checks; the index is what the dispatcher can evaluate without a
        // string compare per node.
        if k.schedule.eligible_when().len() > MAX_SHAPE_RULES {
            return Err(RegistryError::new(
                &k.name,
                format!(
                    "{} shape rules, at most {MAX_SHAPE_RULES}",
                    k.schedule.eligible_when().len()
                ),
            ));
        }
        let mut rules = Vec::new();
        for rule in k.schedule.eligible_when() {
            if rule.axes.len() > MAX_AXES {
                return Err(RegistryError::new(
                    &k.name,
                    format!("rule over {} axes, at most {MAX_AXES}", rule.axes.len()),
                ));
            }
            let mut idx: Vec<String> = rule
                .axes
                .iter()
                .map(|name| {
                    k.axes
                        .iter()
                        .position(|a| a.name == *name)
                        .map(|p| p.to_string())
                        .ok_or_else(|| {
                            RegistryError::new(&k.name, format!("unknown rule axis {name}"))
                        })
                })
                .collect::<Result<Vec<String>, RegistryError>>()?;
            let n_axis = idx.len();
            while idx.len() < MAX_AXES {
                idx.push("-1".to_string());
            }
            rules.push(format!(
                "{{{{{}}}, {n_axis}, {}, {}}}",
                idx.join(", "),
                rule.min,
                rule.max
            ));
        }
        let n_rules = rules.len();
        while rules.len() < MAX_SHAPE_RULES {
            rules.push("{{-1, -1, -1, -1}, 0, 0, 0}".to_string());
        }

        // The width the *nest* needs, not the block: a hierarchical reduction
        // runs 256 lanes on a 32-lane subgroup, and
        // publishing the block would ask every device for a subgroup none has.
        let subgroup = k.subgroup_width();
        let pc_bytes = 4 * shader_params_layout(k).len();
        cpp.push_str(&format!(
            "    {{\"{kernel}\", \"{op}\", {opvar}, \"{vid}\", \"{entry}\", {variant}, \"{artifact}\", {backend}, \
             {priority},\n     {n_rules}, {{{rules}}},\n     {nb}, {np},\n     \
             {{{bindings}}},\n     {{{params}}},\n     \
             {na}, {{{axes}}},\n     {{{dispatch}}},\n     {n_flat}, {{{flat}}},\n     \
             32, {vecw}, {lin}, {rank}, {subg}, {minsg}, {{{wg0}, {wg1}, {wg2}}}, {shb}, {pc}}},\n",
            kernel = k.name,
            opvar = match spec.ggml_op_variant {
                Some(v) => format!("\"{v}\""),
                None => "nullptr".to_string(),
            },
            vid = variant_id(k),
            entry = entrypoint(k),
            variant = match k.schedule.variant() {
                Some(v) => format!("\"{v}\""),
                None => "nullptr".to_string(),
            },
            artifact = crate::manifest::artifact_name(k),
            priority = k.schedule.priority(),
            rules = rules.join(", "),
            backend = backend_enum(ggml_backend(k)),
            nb = k.args.len(),
            np = k.params.len(),
            bindings = bindings.join(", "),
            params = params.join(", "),
            na = k.axes.len(),
            axes = axes.join(", "),
            dispatch = dispatch.join(", "),
            flat = flat.join(", "),
            vecw = k.vector_width(),
            lin = u8::from(k.linear_addr()),
            rank = max_rank(k),
            subg = u8::from(subgroup.is_some()),
            minsg = subgroup.unwrap_or(0),
            wg0 = k.schedule.block()[0],
            wg1 = k.schedule.block()[1],
            wg2 = k.schedule.block()[2],
            shb = crate::manifest::kernel_needs(k).shared_bytes,
            pc = pc_bytes,
        ));
    }
    cpp.push_str("};\n");
    cpp.push_str(&format!(
        "const uint32_t rir_variant_count = {};\n\n",
        variants.len()
    ));

    // The policy table is keyed by **op**, not by kernel, and an op
    // may be served by several kernels - one per `src0` dtype. Two consequences,
    // both handled here rather than left to the consumer:
    //
    // - the four rows are emitted once per op, so `policy_of` cannot read a
    //   duplicate and a second kernel cannot silently change a pair's policy.
    //   Two kernels of one op disagreeing on a backend policy is a generation
    //   error: half an op preferred and half native is not a state the ladder
    //   can express;
    // - the declared domain is the **intersection** of what the kernels declare.
    //   Each says what *it* does not claim; the op leaves to the native kernel
    //   only what none of them claims. A category one kernel covers therefore
    //   disappears from the op's mask, which is exactly what widening a domain
    //   is supposed to look like from outside (ADR-4 section 6).
    cpp.push_str("const rir_op_policy rir_op_policies[] = {\n");
    let mut n_policies = 0usize;
    let mut done: Vec<&str> = Vec::new();
    for spec in specs {
        let Some(op) = spec.ggml_op else { continue };
        if !spec.production || done.contains(&op) {
            continue;
        }
        done.push(op);
        let serving: Vec<&IntegrationSpec> = specs
            .iter()
            .filter(|s| s.production && s.ggml_op == Some(op))
            .collect();
        // The declared domain, as prose above the rows it applies to. The mask
        // is what a consumer checks; the reasons are what the contract requires to be
        // *published* before a native kernel may be kept for a restriction, and
        // a bitmask published alone states nothing a reader can act on. With
        // several kernels per op the reason names its kernel: "dtype" is
        // declared by all of them and each excludes something different.
        let domain = serving
            .iter()
            .fold(u32::MAX, |m, s| m & s.assumed_domain_mask());
        let mut said: Vec<(&str, &str)> = Vec::new();
        for s in &serving {
            for assumption in &s.assumed_domain {
                if assumption.restriction.bit() & domain == 0 {
                    continue; // covered by a sibling kernel, so not the op's
                }
                let line = (assumption.restriction.name(), assumption.why);
                // Kernels of one op usually share a restriction verbatim (the
                // broadcast one below is the same sentence three times); the
                // reason is printed once, and named per kernel only when the
                // kernels give different ones.
                if said.contains(&line) {
                    continue;
                }
                said.push(line);
                let named = serving.len() > 1;
                cpp.push_str(&format!(
                    "    // {op} outside domain - {}{}: {}\n",
                    assumption.restriction.name(),
                    if named {
                        format!(" ({})", s.kernel)
                    } else {
                        String::new()
                    },
                    assumption.why
                ));
            }
        }
        // The chosen native exception (ADR-5 section 5), printed exactly
        // where the domain reasons are and for the same reason: it is the same
        // kind of statement - something RIR does not claim - and a reader of the
        // policy rows must find both in one place. The difference is that no
        // counter can carry it: a node the encoder never offers is not a
        // rejection, so this line *is* the whole record.
        for s in &serving {
            let Some(why) = s.native_exception else {
                continue;
            };
            if domain != 0 {
                return Err(RegistryError::new(
                    format!("{op}/{}", s.kernel),
                    "native exception declared while the declared domain is not empty - \
                     the native kernel is already retained there for the restriction",
                ));
            }
            let line = ("native_exception", why);
            if said.contains(&line) {
                continue;
            }
            said.push(line);
            cpp.push_str(&format!(
                "    // {op} native kernel retained - selected exception: {why}\n"
            ));
        }
        for backend in [
            GgmlBackend::Cuda,
            GgmlBackend::Vulkan,
            GgmlBackend::Metal,
            GgmlBackend::Cpu,
        ] {
            let policy = spec.policy_for(backend);
            for s in &serving {
                if s.policy_for(backend) != policy {
                    return Err(RegistryError::new(
                        format!("{op}/{}", backend.name()),
                        format!(
                            "{} and {} declare two policies for the same op",
                            spec.kernel, s.kernel
                        ),
                    ));
                }
            }
            // Retiring a native is a claim about the *pair*, so every kernel
            // serving the op must agree - and it is only legitimate when the
            // op's declared domain is empty. A pair that publishes a
            // restriction keeps its native kernel for it, so "retired"
            // and "assumed_domain != 0" is a contradiction the generator
            // refuses rather than a state a reader has to notice.
            let retired = serving.iter().any(|s| s.native_retired_on(backend));
            if retired {
                let subject = format!("{op}/{}", backend.name());
                for s in &serving {
                    if !s.native_retired_on(backend) {
                        return Err(RegistryError::new(
                            &subject,
                            format!(
                                "{} retires the native kernel, {} does not",
                                spec.kernel, s.kernel
                            ),
                        ));
                    }
                }
                if domain != 0 {
                    return Err(RegistryError::new(
                        &subject,
                        "native kernel retired while the declared domain is not empty - §11 \
                         permits retaining the native kernel only for a published restriction, \
                         so it may be retired only when there are none",
                    ));
                }
                if !policy.dispatches() {
                    return Err(RegistryError::new(
                        &subject,
                        "native kernel retired under a policy that does not encode the generated kernel",
                    ));
                }
                for s in &serving {
                    if s.native_exception.is_some() {
                        return Err(RegistryError::new(
                            &subject,
                            format!(
                                "{} retires the native kernel while also declaring a native \
                                 exception to retain it",
                                s.kernel
                            ),
                        ));
                    }
                }
            }
            // The forbidden state, refused where it is generated rather than
            // noticed by a reader: promoted, nothing left to close, native still
            // there, and no line saying why. Either the native is retired, or
            // its survival is a *chosen* exception with a reason - never
            // silence. `observe` is outside the rule: such a pair keeps its
            // native because the bench refuses it, which its policy already says.
            if policy.dispatches()
                && domain == 0
                && !retired
                && !serving.iter().any(|s| s.native_exception.is_some())
            {
                return Err(RegistryError::new(
                    format!("{op}/{}", backend.name()),
                    "promoted, no published restriction remains, native kernel retained, and \
                     nothing explains it - either native_retired or a native exception with \
                     its reason (ADR-5 §4, §5)",
                ));
            }
            cpp.push_str(&format!(
                "    {{\"{op}\", {}, {}, {domain}, {}}},\n",
                backend_enum(backend),
                policy_enum(policy),
                u8::from(retired),
            ));
            n_policies += 1;
        }
    }
    cpp.push_str("};\n");
    cpp.push_str(&format!(
        "const uint32_t rir_op_policy_count = {n_policies};\n"
    ));

    Ok((REGISTRY_HEADER.to_string(), cpp))
}
